### ISSUE TITLE
Unable to compile Android - OpenFL 3.2.2  - Lime 2.5.2

### ISSUE THREAD

**Issue by Matan** [HaxeExtension/extension-webview#7]
Hi,

I'm unable to compile this extension with the latest versions of OpenFL and Lime, while not using Legacy mode.

Error:

```
/usr/lib/haxe/lib/extension-webview/1,2,1/extension/webview/WebView.hx:61: characters 11-46 : Class<lime.utils.JNI> has no field createStaticMethod
```

I would help if I knew a bit more about extensions and Android. I guessing the function has moved or changed.

Any help would be great, Thanks!!

**Comment by fbricker** [comment]
Hi, to use most android extensions (including this one), you need to compile your project using legacy mode (-Dlegacy). This is because lime/OpenFL next does not jet provides JNI yet (required to link haxe with Java).
I assume this will be added soon by @jgranick. Until then, you'll need to keep using -Dlegacy to compile on android.

Thanks!

**Comment by Matan** [comment]
Thanks for the info. :)
